name: test_app
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ">=1.0.0 <2.0.0"
  lat_lon_grid_plugin: any
  latlong2: ^0.8.1
  supercluster:
    path: ../../

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
